/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ElementaryCaIndexRouteImport } from './routes/elementary-ca/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElementaryCaIndexRoute = ElementaryCaIndexRouteImport.update({
  id: '/elementary-ca/',
  path: '/elementary-ca/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/elementary-ca/': typeof ElementaryCaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/elementary-ca': typeof ElementaryCaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/elementary-ca/': typeof ElementaryCaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/elementary-ca/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/elementary-ca'
  id: '__root__' | '/' | '/elementary-ca/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ElementaryCaIndexRoute: typeof ElementaryCaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elementary-ca/': {
      id: '/elementary-ca/'
      path: '/elementary-ca'
      fullPath: '/elementary-ca/'
      preLoaderRoute: typeof ElementaryCaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ElementaryCaIndexRoute: ElementaryCaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
